# Generated by Django 5.1.7 on 2025-04-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
    ]
