# Generated by Django 5.1.7 on 2025-04-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_subject_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='duratiob',
            new_name='duration',
        ),
    ]
