# Generated by Django 5.1.7 on 2025-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_average_rating_course_rating_count_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in hours'),
        ),
    ]
