# Generated by Django 5.1.7 on 2025-04-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
