# Generated by Django 5.1.7 on 2025-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_free',
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('started', 'Started'), ('completed', 'Completed')], default='not_started', max_length=11),
        ),
    ]
