# Generated by Django 5.1.7 on 2025-04-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_remove_course_applications_covered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.CharField(max_length=255),
        ),
    ]
