# Generated by Django 5.1.7 on 2025-03-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lecturer",
            table="Lecturer",
        ),
    ]
