# Generated by Django 5.1.7 on 2025-03-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_alter_lecturer_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="course",
            table="Course",
        ),
    ]
