# Generated by Django 5.1.7 on 2025-03-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_alter_course_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="course",
            name="brief",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("unit", models.IntegerField()),
                ("description", models.TextField()),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.course"
                    ),
                ),
            ],
            options={
                "db_table": "Lesson",
            },
        ),
    ]
