# Generated by Django 5.1.7 on 2025-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0004_rename_name_course_title_course_brief_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
