# Generated by Django 5.1.7 on 2025-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0006_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="courseType",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="pic_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
