# Generated by Django 5.1.7 on 2025-04-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_socialmediaconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='blank_profile.png', upload_to='avatars/'),
        ),
    ]
